source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'LifeEngine_Example', :exclusive => true do
  pod "LifeEngine", :path => "../"
end

target 'LifeEngine_Tests', :exclusive => true do
  pod "LifeEngine", :path => "../"

  pod 'Specta'
  pod 'Expecta'
end
